# Generated by Django 3.2.3 on 2021-05-22 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(blank=True, max_length=200, verbose_name='Nome do produto')),
                ('categoria', models.CharField(choices=[('Eletrônicos', 'Eletrônicos'), ('Televisão', 'Televisão'), ('Computador', 'Computador'), ('Celular', 'Celular'), ('Áudio e Vídeo', 'Áudio e Vídeo')], default='Eletrônicos', max_length=20)),
                ('imagem_produto', models.FileField(default='imagens_produtos/default_image.png', upload_to='imagens_produtos/', verbose_name='Foto do produto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('preco_produto', models.FloatField(blank=True, max_length=10, verbose_name='Preço do produto')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código do produto')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL de Pesquisa:')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
