# Generated by Django 3.2.3 on 2021-05-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_imagem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_produto',
            field=models.FileField(blank=True, upload_to='imagens_produtos/', verbose_name='Foto do produto'),
        ),
    ]
