# Generated by Django 3.2.3 on 2021-05-26 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_imagem',
            name='pessoa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario_imagem',
            name='foto_usuario',
            field=models.FileField(blank=True, default='imagens_usuarios/user.png', upload_to='imagens_produtos/', verbose_name='Foto do produto'),
        ),
    ]
