# Generated by Django 3.2.3 on 2021-05-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210526_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_imagem',
            name='foto_usuario',
            field=models.FileField(blank=True, default='imagens_usuarios/user.png', upload_to='imagens_usuarios/', verbose_name='Foto do produto'),
        ),
    ]
